import {   
  Text,
  Tooltip,
Button } from '@chakra-ui/react'
import { useDisclosure } from '@chakra-ui/hooks' 

import Head from 'next/head'
import { ThemeProvider } from '../components/ThemeContext';
import Toggle from '../components/ThemeToggle';
import CardProject from '../components/CardProject';
import Link from 'next/link'
import warapo from '../public/warapo.jpg'
import croco_sign from '../public/croco-sign.png'
import justship from '../public/justship.png'



export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure()

      
  
  return (
    <ThemeProvider>
       <div className="absolute left-0 top-0 ml-4 mt-4 md:ml-6 md:mt-4">
          <Toggle />
        </div>
     
     
        
  
    <div className="dark:bg-gray-800 bg-gray-100 dark:text-white text-gray-800" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul className='flex flex-row justify-center md:justify-end
      pt-4 gap-8 md:gap-4 md:mr-20 md:text-lg'
    
      >        
        <li><a href="#">Projects</a></li>
        
        <li>
          <Link href='/posts'><a>Blog</a></Link>
        </li>
        
        <li>About me</li>
      
      </ul>
      <div className="flex flex-col items-center gap-2">
          <h1 className=" md:text-left md:mr-32 xl:mr-56
          mt-10 md:mt-20 
          text-3xl md:text-7xl lg:text-9xl"
          
          
          >
            Hello. <br></br> <span>I am Kevin</span> 
          </h1>
          
          <Tooltip className="md:text-left -mr-5 md:mr-10"label="Working with React and Phoenix" hasArrow><span className="text-base md:text-2xl lg:text-4xl">Web Developer</span></Tooltip>
        </div>
        <div className="flex justify-center md:absolute md:right-28 md:top-24">
          <div className="flex justify-center items-center
          rounded-full border-2 dark:border-pink-300 border-pink-500 animate-pulse
          w-32 h-32 lg:w-48 lg:h-48 text-lg lg:text-xl font-semibold mt-7 md:mt-0 md:text-xl" 
          >See my work</div>
        </div>
      <div className='flex justify-center mt-7 md:mt-14'>
        <p className='w-56 md:w-72 text-left md:text-lg'>Lorem impsum Lorem impsum Lorem impsum Lorem impsum Lorem impsum Lorem impsumLorem impsum Lorem impsum Lorem impsumLorem impsum Lorem impsum Lorem impsumLorem impsum Lorem impsum Lorem impsumLorem impsum Lorem impsum Lorem impsum</p>
      </div>
      <div className='flex flex-col items-center gap-10 mt-10'>
      <h2 className="text-3xl">Projects<span className='text-pink-500 dark:text-pink-300 h-5 absolute -mt-11  text-7xl pl-2 animate-pulse '>__</span></h2>
      <CardProject
      img={warapo}
      name='Warapo'
      type='Freelancer Project'
      text="A freelancer project using Gatsby, ChakraUI, Graphql, Woocommerce. The website's goal is sell merchandasing and reserve tickets to parties"
      link='https://warapocuba.com/'
      ></CardProject>
      <CardProject
       name='Crocosign'
      img={croco_sign}
      type='Beta'
      text="Desing Agency Website's example using Nuxt and GSAP. I learned how to build fancy animations using GSAP"
      link='https://croco-sign.vercel.app/'
      ></CardProject>
      <CardProject
      name='JustShip'
      type='Beta'
      img={justship}
      text="It was the first landing page JustShipt.to. I build this website using Nuxt and TailwindCSS"
      link='https://just-ship-beta.vercel.app/'
      ></CardProject>
      </div>  
      </div>
     
      </ThemeProvider>
      
  )
}